import 'dart:convert';

import 'package:xml/xml.dart';
import 'package:zatca_flutter/local_store.dart';
import 'package:zatca_flutter/model/my_business_info.dart';
import 'package:zatca_flutter/model/xml/invoice_line.dart';
import 'package:zatca_flutter/model/xml/invoice_type_code.dart';
import 'package:zatca_flutter/model/xml/legal_monetary_total.dart';
import 'package:zatca_flutter/model/xml/tax_details.dart';
import 'package:zatca_flutter/service/util.dart';

import 'party.dart';

/// A class representing a simplified invoice used for transactions.
///
/// The [SimplifiedInvoice] class holds all necessary data for an invoice, including
/// the supplier and customer information, the invoice lines (items), tax details,
/// and other related fields. It can also generate both a JSON and an XML representation
/// of the invoice, suitable for reporting and invoicing purposes.
class SimplifiedInvoice {
  /// Unique identifier for the invoice.
  final String id;

  /// ICV (Invoice Counter Value): It is a sequential and unique counter that increments with each invoice generated by a specific device/environment.
  final int icv;

  /// Universal Unique Identifier (UUID) for the invoice.
  final String uuid;

  /// The date the invoice was issued.
  final DateTime issueDate;

  /// The time the invoice was issued.
  final DateTime issueTime;

  /// Currency used in the invoice (e.g., SAR for Saudi Riyals).
  final String currency;

  /// The customer to whom the invoice is addressed.
  final IndividualParty? customer;

  /// The list of items (invoice lines) associated with the invoice.
  final List<InvoiceLine> lines;

  /// The tax details related to the invoice.
  final TaxDetails tax;

  /// The legal monetary total of the invoice (e.g., subtotal, taxes, total).
  final LegalMonetaryTotal monetaryTotal;

  /// PIH (Previous Invoice Hash): A hash (cryptographic value) of the previous invoice issued.
  final String pih;

  /// Invoice Type Code
  final InvoiceTypeCode? invoiceTypeCode;

  /// The supplier information, fetched from local storage.
  MyBusinessInfo? get supplier => LocalStore.instance.myBusinessInfo;

  /// Constructor to initialize the [SimplifiedInvoice] object with necessary values.
  SimplifiedInvoice({
    required this.icv,
    required this.id,
    required this.uuid,
    required this.issueDate,
    required this.issueTime,
    required this.currency,
    this.customer,
    required this.lines,
    required this.tax,
    required this.monetaryTotal,
    required this.pih,
    this.invoiceTypeCode,
  });

  /// Converts the [SimplifiedInvoice] object to a JSON format.
  ///
  /// This method returns the invoice details as a map of key-value pairs that represent
  /// the JSON structure. It includes details such as the ID, issue date, issue time, customer,
  /// tax information, and invoice lines.
  ///
  /// Returns a [Map<String, dynamic>] representing the invoice in JSON format.
  Map<String, dynamic> toJson() {
    return {
      "id": id,
      "uuid": uuid,
      "issueDate": issueDate.toIso8601String().split('T')[0],
      "issuedTime": issueTime.toIso8601String().split('T')[1].split('.')[0],
      "currency": currency,
      "supplier": supplier,
      "customer": customer,
      "lines": lines.map((item) => item.toJson()).toList(),
      "tax": tax.toJson(),
    };
  }

  /// Converts the [SimplifiedInvoice] object to a JSON string.
  ///
  /// This method converts the invoice's JSON representation to a JSON string using
  /// [jsonEncode].
  ///
  /// Returns the invoice as a [String] in JSON format.
  String toJsonString() => jsonEncode(toJson());

  /// Generates the XML representation of the invoice.
  ///
  /// This method creates an XML document structured with all the required elements for
  /// the invoice, including information such as the invoice ID, customer details, items,
  /// tax information, and supplier details. It also adds additional document references,
  /// and handles the inclusion of tax totals and monetary totals.
  ///
  /// Returns the XML string representing the invoice.
  String toXml() {
    final builder = XmlBuilder();
    builder.processing('xml', 'version="1.0" encoding="UTF-8"');
    builder.element('Invoice', namespaces: {
      "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2": "",
      "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2":
          "cac",
      "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2":
          "cbc",
      "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2":
          "ext"
    }, nest: () {
      builder.element('cbc:ProfileID', nest: 'reporting:1.0');
      builder.element('cbc:ID', nest: id);
      builder.element('cbc:UUID', nest: uuid);
      builder.element('cbc:IssueDate',
          nest: issueDate.toIso8601String().split('T')[0]);
      builder.element('cbc:IssueTime',
          nest: issueTime.toIso8601String().split('T')[1].split('.')[0]);

      // Invoice Type Code
      invoiceTypeCode != null
          ? invoiceTypeCode?.toXml(builder)
          : InvoiceTypeCode.simplifiedTaxInvoice();

      builder.element('cbc:DocumentCurrencyCode', nest: currency);
      builder.element('cbc:TaxCurrencyCode', nest: currency);

      // Additional Document Reference for ICV
      builder.element('cac:AdditionalDocumentReference', nest: () {
        builder.element('cbc:ID', nest: 'ICV');
        builder.element('cbc:UUID', nest: icv);
      });

      // Additional Document Reference for PIH
      builder.element('cac:AdditionalDocumentReference', nest: () {
        builder.element('cbc:ID', nest: 'PIH');
        builder.element('cac:Attachment', nest: () {
          builder.element('cbc:EmbeddedDocumentBinaryObject',
              attributes: {'mimeCode': 'text/plain'},
              nest: pih.isEmpty ? getPIHForFirstInvoice() : pih);
        });
      });

      // Supplier and Customer parties
      builder.element('cac:AccountingSupplierParty',
          nest: () => supplier?.toXml(builder));
      if (customer != null) {
        builder.element('cac:AccountingCustomerParty',
            nest: () => customer?.toXml(builder));
      }

      // Tax total and Legal Monetary total
      builder.element('cac:TaxTotal', nest: () {
        builder.element('cbc:TaxAmount',
            attributes: {'currencyID': tax.currency}, nest: tax.amount);
      });
      builder.element('cac:TaxTotal', nest: () => tax.toXml(builder));
      builder.element('cac:LegalMonetaryTotal',
          nest: () => monetaryTotal.toXml(builder));

      // Invoice Lines
      for (int id = 0; id < lines.length; id++) {
        InvoiceLine line = lines[id];
        builder.element('cac:InvoiceLine', nest: () => line.toXml(builder, id));
      }
    });

    return builder.buildDocument().toXmlString(pretty: true);
  }

  /// Generates and saves the XML representation of the invoice to a file.
  ///
  /// This method uses the [toXml()] method to generate the XML and then saves it to a file
  /// using the provided [fileName]. The method is asynchronous.
  Future<void> generateAndSaveXml(String fileName) async {
    await saveToFile(toXml(), fileName);
  }
}
